# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_change_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[(b'tristezza', b'Tristezza'), (b'rabbia', b'Rabbia'), (b'sorpresa', b'Sorpresa'), (b'gioia', b'Gioia'), (b'disprezzo', b'Disprezzo'), (b'disgusto', b'Disgusto'), (b'paura', b'Paura'), (b'vergogna', b'Vergogna')], db_index=True, default=b'gioia', max_length=30)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('slug',),
                'verbose_name': 'Emotion',
                'verbose_name_plural': 'Emotions',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_change_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('query', models.CharField(max_length=140)),
                ('nlp_analysis', models.TextField(default=b'', help_text='json dump of Google NLP analysis')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('last_change_date',),
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
            },
        ),
    ]
