# -*- coding: utf-8 -*-
SORROW = 'tristezza'
ANGER = 'rabbia'
SURPRISE = 'sorpresa'
JOY = 'gioia'
CONTEMPT = 'disprezzo'
DISGUST = 'disgusto'
FEAR = 'paura'
SHAME = 'vergogna'

EMOTION_CATEGORIES_CHOICES = (
    (SORROW, 'Tristezza'),
    (ANGER, 'Rabbia'),
    (SURPRISE, 'Sorpresa'),
    (JOY, 'Gioia'),
    (CONTEMPT, 'Disprezzo'),
    (DISGUST, 'Disgusto'),
    (FEAR, 'Paura'),
    (SHAME, 'Vergogna'),
)

EMOTIONS = {
    SORROW: [
        "abbandono", "abbandonare", "abbandonato",
        "abbattimento", "abbattere", "abbattuto",
        "accasciare", "accasciato",
        "addoloramento", "addolorare", "addolorato",
        "afflizione", "affliggimento", "affliggere", "afflitto",
        "affrangere", "affranto",
        "amarezza", "amareggiare", "amareggiato",
        "angoscia", "angosciare", "angosciato",
        "autocommiserare", "autocommiserazione",
        "avvilimento", "avvilire", "avvilito", "avvilente",
        "bisognoso",
        "colpevolezza", "incolpare", "colpevolizzare", "colpevole", "colpevolmente",
        "contrizione", "contrire", "contrito",
        "cupezza", "incupire", "cupo", "cupamente",
        "delusione", "deludere", "deluso", "deludente",
        "depressione", "deprimere", "depresso",
        "desolazione", "desolare", "desolato", "desolante",
        "disillusione", "disilludere", "disilluso",
        "disperazione", "disperare", "disperato", "disperatamente",
        "dolore", "dolere", "dolente",
        "ferita", "ferire", "ferito",
        "frustrazione", "frustrare", "frustrato", "frustrante",
        "infelicità", "infelice", "infelicemente",
        "insoddisfazione", "insoddisfatto", "insoddisfacente",
        "isolamento", "isolare", "isolatamente",
        "malinconia", "malinconico", "malinconicamente",
        "mestizia", "mesto", "mestamente",
        "noia", "annoiare", "annoiato",
        "nostalgia", "nostalgico", "nostalgicamente",
        "oppressione", "opprimere", "oppresso", "opprimente",
        "pena", "penare", "penoso", "penosamente",
        "penitente",
        "perdita", "perdere", "perduto", "perdente",
        "prostrazione", "prostrare", "prostrato",
        "rassegnazione", "rassegnare", "rassegnato", "rassegnatamente",
        "rattristare", "rattristato",
        "rimordere", "rimorso",
        "rimpianto", "rimpiangere",
        "rincrescimento", "rincrescere", "rincresciuto",
        "sconforto", "sconfortare", "sconfortato", "sconfortante",
        "scontento", "scontentare",
        "scoraggiamento", "scoraggiare", "scoraggiato", "scoraggiante", "scoraggiatamente",
        "sofferenza", "soffrire", "sofferto", "sofferente",
        "solitudine",
        "squallore", "squallido",
        "stufo", "stufare",
        "svilire", "svilito", "svilente",
        "tetro", "tetramente",
        "tormento", "tormentare", "tormentato", "tormentosamente",
        "trasandato", "trasandatamente",
        "trascuratezza", "trascurare", "trascurato", "trascuratamente",
        "tristezza", "intristire", "triste", "tristemente",
    ],
    ANGER: [
        "acrimonia", "acrimonioso", "acrimoniosamente",
        "alterazione", "alterare", "alterato",
        "animosità", "animoso", "animosamente",
        "arrabbiatura", "arrabbiare", "arrabbiato",
        "astio", "astioso", "astiosamente",
        "collera", "collerico", "collericamente",
        "esasperazione", "esasperare", "esasperato", "esasperatamente",
        "furia", "furibondo", "furioso", "furiosamente",
        "gelosia", "ingelosire", "geloso", "gelosamente",
        "impaziente", "impazientememte",
        "incavolatura", "incavolare", "incavolato",
        "incazzatura", "incazzare", "incazzato",
        "indignazione", "indignare", "indignato",
        "inferocito",
        "infuriare", "infuriato",
        "intrattabile", "intrattabilmente",
        "invidia", "invidiare", "invidioso", "invidiosamete",
        "ira", "irare", "irato", "iratamente",
        "irritabilità", "irritazione", "irritare", "irritabile", "irritabile", "irritevole", "irritevolmente",
        "odio", "odiare", "odioso", "odiare", "odiosamente",
        "offesa", "offendere", "offeso", "offensivo", "offensivamente",
        "ostilità", "ostile", "ostilmente",
        "permalosità", "permaloso",
        "rabbia", "rabbioso", "rabbiosamente",
        "risentimento", "risentire", "risentitamente", "risentito",
        "scontrosità", "scontroso",
        "stizza", "stizzire", "stizzosamente", "stizzoso",
        "suscettibilità", "suscettibile", "suscettibilmente",
        "vendetta", "vendicare", "vendicativamente", "vendicativo", "vendicatore",
        "violenza", "violento", "violentemente",
    ],
    SURPRISE: [
        "annebbiato",
        "attonimento",
        "caotico",
        "colpito",
        "confuso",
        "disarmonico",
        "disordinato",
        "disorganizzato",
        "diverso",
        "esterrefatto",
        "impressionato",
        "incantato",
        "incasinato",
        "incoerente",
        "incomprensibile",
        "incredulo",
        "indistinto",
        "meraviglia",
        "meravigliato",
        "mescolato",
        "mischiato",
        "oscuro",
        "particolare",
        "sbalestrato",
        "sbalordimento",
        "sbalordito",
        "sbigottito",
        "sbilanciato",
        "scioccato",
        "sconcertato",
        "sconcerto",
        "sconnesso",
        "sgomentato",
        "singolare",
        "sorpresa",
        "sorpreso",
        "sottosopra",
        "squilibrato",
        "stralunato",
        "strambo",
        "strampalato",
        "strano",
        "stupefatto",
        "stupito",
        "stupore",
        "trasecolato",
        "vago",
    ],
    JOY: [
        "accettazione",
        "adorazione",
        "affabile",
        "affettuoso",
        "affinità",
        "allegro",
        "appagato",
        "beatitudine",
        "bene",
        "benevolenza",
        "caloroso",
        "capriccio",
        "compiaciuto",
        "contentezza",
        "contento",
        "desidera",
        "desiderare",
        "desideri",
        "desiderio",
        "devozione",
        "diletto",
        "divertimento",
        "divertito",
        "eccitato",
        "entusiasmo",
        "esaltato",
        "esaltazione",
        "espansivo",
        "estasi",
        "euforico",
        "felice",
        "felicità",
        "festoso",
        "fiducioso",
        "fierezza",
        "gaio",
        "gioia",
        "gioioso",
        "gioviale",
        "godimento",
        "gratificazione",
        "infatuazione",
        "interessato",
        "lieto",
        "ottimista",
        "piacere",
        "quieto",
        "serenità",
        "sereno",
        "soddisfatto",
        "soddisfazione",
        "sollevato",
        "sollievo",
        "spensierato",
        "speranzoso",
        "tenero",
    ],
    CONTEMPT: [
        "aborrimento",
        "avversione",
        "disprezzo", "disprezzare", "disprezzato",
        "sdegno",
    ],
    DISGUST: [
        "avverso",
        "disgusto", "disgustare", "disgustato",
        "fastidio",
        "infastidire", "infastidito",
        "inorridito", "inorridire",
        "nausea", "nauseare", "nauseato",
        "repulsione",
        "ribrezzo",
        "ripugnanza", "ripugnare", "ripugnato", "ripugnante",
        "rivoltato",
        "scandalizzare", "scandalizzato",
        "schifo", "schifare", "schifato", "schifiltoso",
        "stomachevolezza", "stomachevole", "stomacare", "stomacato",
        "urtare", "urtato",
        "voltastomaco",
    ],
    FEAR: [
        "agitato",
        "allarmato",
        "ansia",
        "ansioso",
        "apprensione",
        "apprensivo",
        "atterrito",
        "cautela",
        "chiuso",
        "contratto",
        "diffidente",
        "dubbioso",
        "esitante",
        "esitazione",
        "fobia",
        "goffo",
        "impacciato",
        "impaurito",
        "incerto",
        "inquieto",
        "insicuro",
        "intimorito",
        "irrigidito",
        "nervosismo",
        "nervoso",
        "panico",
        "paura",
        "pauroso",
        "pavido",
        "preoccuparsi",
        "preoccupata",
        "preoccupati",
        "preoccupato",
        "preoccupazione",
        "preoccupazioni",
        "ritroso",
        "sconvolto",
        "spaventato",
        "spavento",
        "tensione",
        "terrore",
        "teso",
        "timido",
        "timore",
        "timoroso",
        "umile",
    ],
    SHAME: [
        "imbarazzo", "imbarazzare", "imbarazzato",
        "mortificazione", "mortificare", "mortificato", "mortificante",
        "rossore", "arrossire", "arrossito",
        "pentimento", "pentire", "pentito",
        "pudicizia", "pudico",
        "pudore",
        "riguardo",
        "ritegno",
        "umiliazione", "umiliare", "umiliante", "umiliato",
        "vergogna", "vergognare", "vergognato",
    ],
}
