# -*- coding: utf-8 -*-
SORROW = 'tristezza'
ANGER = 'rabbia'
SURPRISE = 'sorpresa'
JOY = 'gioia'
CONTEMPT = 'disprezzo'
DISGUST = 'disgusto'
FEAR = 'paura'
SHAME = 'vergogna'

EMOTION_CATEGORIES_CHOICES = (
    (SORROW, 'Tristezza'),
    (ANGER, 'Rabbia'),
    (SURPRISE, 'Sorpresa'),
    (JOY, 'Gioia'),
    (CONTEMPT, 'Disprezzo'),
    (DISGUST, 'Disgusto'),
    (FEAR, 'Paura'),
    (SHAME, 'Vergogna'),
)

EMOTIONS = {
    SORROW: [
        "abbandono", "abbandonare", "abbandonato",
        "abbattimento", "abbattere", "abbattuto",
        "accasciare", "accasciato",
        "addoloramento", "addolorare", "addolorato",
        "afflizione", "affliggimento", "affliggere", "afflitto",
        "affrangere", "affranto",
        "amarezza", "amareggiare", "amareggiato",
        "angoscia", "angosciare", "angosciato",
        "autocommiserare", "autocommiserazione",
        "avvilito",
        "bisognoso",
        "colpevole",
        "cupezza",
        "cupo",
        "deludente",
        "deludenti",
        "delusa",
        "delusi",
        "delusione",
        "delusioni",
        "deluso",
        "depresso",
        "desolato",
        "disilluso",
        "disperato",
        "disperazione",
        "dolente",
        "dolore",
        "ferito",
        "frustrato",
        "frustrazione",
        "frustrazioni",
        "infelice",
        "insoddisfatto",
        "malinconia",
        "malinconico",
        "mancanza d’allegria",
        "mesto",
        "mortificato",
        "noia", "annoiare", "annoiato",
        "nostalgico",
        "oppresso",
        "pena",
        "penoso",
        "pentire",
        "perdente",
        "pessimista",
        "prostrato",
        "rassegnazione",
        "rattristato",
        "rimorso",
        "rimpianto",
        "sconfortato",
        "sconforto",
        "scontento",
        "scoraggiato",
        "senso di colpa",
        "sofferenza",
        "soffrire",
        "solitudine",
        "squallido",
        "stufo",
        "svilito",
        "tetro",
        "tormentato",
        "trasandato",
        "trascurato",
        "triste",
        "tristezza",
        "umiliato",
    ],
    ANGER: [
        "acrimonia",
        "alterato",
        "amarezza",
        "animosità",
        "arrabbiato",
        "astioso",
        "collera",
        "collerico",
        "esasperazione",
        "fastidio",
        "furia",
        "furibondo",
        "furioso",
        "gelosia",
        "geloso",
        "impaziente",
        "incavolato",
        "incazzato",
        "indignato",
        "indignazione",
        "inferocito",
        "intrattabile",
        "invidia",
        "invidioso",
        "ira",
        "irato",
        "irritabile",
        "irritabilità",
        "irritazione",
        "odio",
        "offesa",
        "offeso",
        "ostilità",
        "permaloso",
        "rabbia",
        "risentimento",
        "risentito",
        "scontroso",
        "sdegno",
        "stizzoso",
        "suscettibile",
        "vendicativo",
        "violenza",
    ],
    SURPRISE: [
        "annebbiato",
        "attonimento",
        "caotico",
        "colpito",
        "confuso",
        "disarmonico",
        "disordinato",
        "disorganizzato",
        "diverso",
        "esterrefatto",
        "impressionato",
        "incantato",
        "incasinato",
        "incoerente",
        "incomprensibile",
        "incredulo",
        "indistinto",
        "meraviglia",
        "meravigliato",
        "mescolato",
        "mischiato",
        "oscuro",
        "particolare",
        "riguardo",
        "ritegno",
        "sbalestrato",
        "sbalordimento",
        "sbalordito",
        "sbigottito",
        "sbilanciato",
        "scioccato",
        "sconcertato",
        "sconcerto",
        "sconnesso",
        "sgomentato",
        "singolare",
        "sorpresa",
        "sorpreso",
        "sottosopra",
        "squilibrato",
        "stralunato",
        "strambo",
        "strampalato",
        "strano",
        "stupefatto",
        "stupito",
        "stupore",
        "trasecolato",
        "vago",
    ],
    JOY: [
        "accettazione",
        "adorazione",
        "affabile",
        "affettuoso",
        "affinità",
        "allegro",
        "appagato",
        "beatitudine",
        "bene",
        "benevolenza",
        "caloroso",
        "capriccio",
        "compiaciuto",
        "contentezza",
        "contento",
        "desidera",
        "desiderare",
        "desideri",
        "desiderio",
        "devozione",
        "diletto",
        "divertimento",
        "divertito",
        "eccitato",
        "entusiasmo",
        "esaltato",
        "esaltazione",
        "espansivo",
        "estasi",
        "euforico",
        "felice",
        "felicità",
        "festoso",
        "fiducioso",
        "fierezza",
        "gaio",
        "gioia",
        "gioioso",
        "gioviale",
        "godimento",
        "gratificazione",
        "infatuazione",
        "interessato",
        "lieto",
        "ottimista",
        "piacere",
        "quieto",
        "serenità",
        "sereno",
        "soddisfatto",
        "soddisfazione",
        "sollevato",
        "sollievo",
        "spensierato",
        "speranzoso",
        "tenero",
    ],
    CONTEMPT: [
        "indignato",
        "avversione",
        "aborrimento",
        "sdegno",
        "disprezzo",
    ],
    DISGUST: [
        "disgusto", "disgustare", "disgustato",
        "repulsione",
        "voltastomaco",
        "schifo", "schifare", "schifato", "schifiltoso",
        "nausea", "nauseare", "nauseato",
        "avverso",
        "infastidire", "infastidito",
        "inorridito", "inorridire",
        "nausea", "nauseare", "nauseato",
        "ripugnanza", "ripugnare", "ripugnato", "ripugnante",
        "rivoltato",
        "scandalizzare", "scandalizzato",
        "stomachevolezza", "stomachevole", "stomacare", "stomacato",
        "urtare", "urtato",
        "ribrezzo",
        "fastidio", "infastidire", "infastidito",
        "avversione",
        "disprezzo", "disprezzare", "disprezzato",
    ],
    FEAR: [
        "agitato",
        "allarmato",
        "angoscia",
        "ansia",
        "ansioso",
        "apprensione",
        "apprensivo",
        "atterrito",
        "cautela",
        "chiuso",
        "contratto",
        "diffidente",
        "dubbioso",
        "esitante",
        "esitazione",
        "fobia",
        "geloso",
        "goffo",
        "imbarazzato",
        "impacciato",
        "impaurito",
        "incerto",
        "inquieto",
        "insicuro",
        "intimorito",
        "irrigidito",
        "nervosismo",
        "nervoso",
        "panico",
        "paura",
        "pauroso",
        "pavido",
        "preoccuparsi",
        "preoccupata",
        "preoccupati",
        "preoccupato",
        "preoccupazione",
        "preoccupazioni",
        "ritroso",
        "sconvolto",
        "spaventato",
        "spavento",
        "tensione",
        "terrore",
        "teso",
        "timido",
        "timore",
        "timoroso",
        "umile",
        "vergognato",
    ],
    SHAME: [
        "vergogna", "vergognare", "vergognato",
        "mortificazione", "mortificare", "mortificato",
        "rossore", "arrossire", "arrossito",
        "pentire", "pentimento", "pentito",
        "pudore",
        "pudico",
        "riguardo",
        "ritegno",
        "umiliazione", "umiliare", "umiliato",
        "imbarazzo", "imbarazzare", "imbarazzato",
    ],
}
